### ISSUE TITLE
Suggestions for Drawing out BezierCurves

### ISSUE THREAD

**Issue by yozef** [McDo/Tibezier#1]
One Solution I found is http://drawscri.pt/ which converts from Adobe Illustrator to Obj-C, which will be "easier" to convert to McDo's JS objects for drawing. 

Anybody has any other suggestions?

**Comment by McDo** [comment]
[Paint Code](http://www.paintcodeapp.com/) is really awesome as well.

**Comment by yozef** [comment]
@McDo I'm sold 😃

**Comment by McDo** [comment]
@yozef pretty cool tool that helps me a lot, bet you gonna love with it~
